[package]
name = "fluxcell-magic-link"
version = "0.1.0"
edition = "2024"
description = "Magic Link Authentication Fluxcell for SpectraGQL"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
uuid = { version = "1.16.0", features = ["v4", "v7"] }
